name: mighty_meditation
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #BASE
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.3
  intl: ^0.17.0

  #UI
  cached_network_image: ^3.2.3
  flutter_staggered_animations: ^1.1.1
  flutter_vector_icons: ^2.0.0
  lottie: ^2.3.0

  #STATE MANAGEMENT
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5


  #CONNECTIVITY
  http: ^0.13.5
  connectivity_plus: ^3.0.3
  package_info_plus: ^3.0.3
  share_plus: ^6.3.1
  store_redirect: ^2.0.1

  # WEB TOOLS
  flutter_inappwebview: ^5.7.2+3

  # ADS
  google_mobile_ads: ^2.3.0
  facebook_audience_network: ^1.0.1

  # PUSH NOTIFICATION
  onesignal_flutter: ^3.5.1

  # LAUNCH URL
  url_launcher: ^6.1.10

  #Database
  shared_preferences: ^2.0.20

  #Audio
  assets_audio_player: ^3.0.6

  #IOS
  app_tracking_transparency: ^2.0.3

  # Other
  fluttertoast: ^8.2.1
  html: ^0.15.2
  sliding_up_panel: ^2.0.0+1

  #Localization
  flutter_localizations:
    sdk: flutter

#dependency_overrides:
#  mobx: ^2.0.7+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - asset/
